[package]
name = "coverm"
version = "0.2.0-alpha6"
authors = ["Ben Woodcroft <benjwoodcroft@gmail.com>"]
license = "GPL-3.0"
description = "Read coverage calculator for metagenomics"
homepage = "https://github.com/wwood/CoverM"
repository = "https://github.com/wwood/CoverM"
documentation = "https://github.com/wwood/CoverM"
readme = "README.md"

[dependencies]
bio = "0.25.*"
rust-htslib = "0.22.*"
clap = "2.*"
log = "0.4.*"
env_logger = "0.6.*"
nix = "0.13.*"
tempdir = "0.3.*"
tempfile = "3.0.*"
ansi_term = "0.11"
lazy_static = "1.3.0"
fastq = "0.6.*"

[dev-dependencies]
assert_cli = "0.6.*"
